[build]
  command = "curl -fSL https://github.com/rust-lang/mdBook/releases/download/v0.3.7/mdbook-v0.3.7-x86_64-unknown-linux-gnu.tar.gz -o /tmp/ && tar -xvf /tmp/mdbook-v0.3.7-x86_64-unknown-linux-gnu.tar.gz && cd mdbook && ./tmp/mdbook build"
  publish = "mdbook/book"
