[build]
  command = "curl -L https://github.com/rust-lang/mdBook/releases/download/v0.3.7/mdbook-v0.3.7-x86_64-unknown-linux-gnu.tar.gz | tar xvz && mv mdbook /usr/locab/bin/mdbook && cd mdbook && mdbook build"
  publish = "mdbook/book"